apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple1
  labels:
    app: simple1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple1
  template:
    metadata:
      labels:
        app: simple1
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.32.0
        args:
          - server
        ports:
        - containerPort: 9085
--- 
apiVersion: v1
kind: Service
metadata:
  name: simple1
spec:
  selector:
    app: simple1
  ports:
    - protocol: TCP
      port: 9085
      targetPort: 9085
