apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: jsonnet-sample
  labels:
    env: example
    team: dev
  input:
    customTemplating:
      command: "jsonnet"
      args:
        - "-y"
        - "-e"
        - '(import "dev.libsonnet").all'
      externalTool:
        package: jsonnet
        version: 0.19.1
