apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: jsonnet-sample
  labels:
    env: example
    team: dev
  input:
    customTemplating:
      command: "jsonnet"
      args:
        - "-y"
        - "-e"
        - '(import "dev.libsonnet").all'
      version: 0.19.1
      installScriptTemplate: |
        cd {{ .WorkingDir }}
        curl -L https://github.com/google/jsonnet/archive/refs/tags/v{{ .Version }}.tar.gz | tar xvz
        cd jsonnet-{{ .Version }}
        make
        mv jsonnet {{ .BinDir }}/jsonnet-{{ .Version }}
        chmod +x {{ .BinDir }}/jsonnet-{{ .Version }}
